### ISSUE TITLE
Support Schema validator

### ISSUE THREAD

**Issue by tuongbuimtt** [ibireme/yyjson#156]
Would you have a plan supporting the schema validator?

A function that can validate the input JSON data whether obeys the given JSON schema?

**Comment by ibireme** [comment]
I once considered supporting JSON schema but found that it requires regex support. 

Unfortunately, C doesn't have built-in regex, and adding regex or third-party libraries would complicate things. So, there's no plan to support JSON schema for now.

**Comment by MaxBrandtner** [comment]
@ibireme is there a json-schema library that uses yyjson already (or another decently fast c json-schema library). If not I'd be willing to step in. (I'm not interested in duplicating work that has already been done before though) Unfortunately, it seems to me that some features of json-schema (refs, url lookups, ecma compliant regex) make it impossible to implement it in an efficient manner. Backtracking breaks the pumping lemma so an NFA (or dynDFA) regex engine(like PCRE2) would have to be used (instead of something like re2).

In any case it sounds like a bunch of work, but if it hasn't been done I'd be willing to give it a shot.

**Comment by ibireme** [comment]
> is there a json-schema library that uses yyjson already (or another decently fast c json-schema library).

@MaxBrandtner  Currently, no.

But I found a C++ library called [blaze](https://github.com/sourcemeta/blaze) that claims to be super fast at JSON schema validation, might be worth checking out. Looks like building full JSON schema support from scratch is pretty complicated.
